let products = [{name: 'Blueberry Yogurt Pack', picture: 'yogurtcup', price: '5.99', aisle: 'Dairy & Eggs'},
    {name: '10 Large White Eggs', picture: '10whiteeggs', price: '2.99', aisle: 'Dairy & Eggs'},
    {name: '10 Large Brown Eggs', picture: '12browneggs', price: '4.69', aisle: 'Dairy & Eggs'},
    {name: '1% Milk (1 L)', picture: '1milk1L', price: '1.85', aisle: 'Dairy & Eggs'},
    {name: '1% Milk (4 L)', picture: '1milk4L', price: '6.38', aisle: 'Dairy & Eggs'},
    {name: '2% Milk (1 L)', picture: '2milk1L', price: '1.93', aisle: 'Dairy & Eggs'},
    {name: '2% Milk (4 L)', picture: '2milk4L', price: '6.68', aisle: 'Dairy & Eggs'},
    {name: '30 Eggs', picture: '30eggs', price: '4.77', aisle: 'Dairy & Eggs'},
    {name: 'Honeycrisp Apple', picture: 'apple', price: '1.05', aisle: 'Fruits & Vegetables'},
    {name: 'Banana', picture: 'banana', price: '0.33', aisle: 'Fruits & Vegetables'},
    {name: 'French Baguette', picture: 'Brearolls', price: '2.49', aisle: 'Bakery'},
    {name: 'Celery', picture: 'celery', price: '3.69', aisle: 'Fruits & Vegetables'},
    {name: 'Cheddar Cheese', picture: 'cheddarcheese', price: '4.49', aisle: 'Dairy & Eggs'},
    {name: 'Boneless Chicken, 3-Pack', picture: 'chickenbreast', price: '5.11', aisle: 'Butchery'},
    {name: 'Chocolate Chips', picture: 'chocolatechip', price: '16.99', aisle: 'Non-Perishable'},
    {name: 'Cream of Mushroom Soup', picture: 'creamofmushroom', price: '3.29', aisle: 'Non-Perishable'},
    {name: 'English Cucumber', picture: 'cucumber', price: '2.50', aisle: 'Fruits & Vegetables'},
    {name: 'Diced Tomatoes', picture: 'dicedtomatoes', price: '0.99', aisle: 'Non-Perishable'},
    {name: 'Confit Duck Leg, 2-Pack', picture: 'duckconfit', price: '8.50', aisle: 'Butchery'},
    {name: 'All Purpose Flour', picture: 'flour', price: '8.29', aisle: 'Non-Perishable'},
    {name: 'Frozen Pepperoni & Cheese Pizza', picture: 'FrozenPizza', price: '6.99', aisle: 'Frozen'},
    {name: 'Frozen Chopped Spinach', picture: 'FrozenSpinach', price: '2.99', aisle: 'Frozen'},
    {name: 'Canned Green Peas', picture: 'cannedpeas', price: '1.69', aisle: 'Non-Perishable'},
    {name: 'Lean Ground Beef', picture: 'groundbeef', price: '7.73', aisle: 'Butchery'},
    {name: 'Haddock Fillet', picture: 'haddockfillet', price: '1.76', aisle: 'Butchery'},
    {name: 'Vanilla Ice Cream', picture: 'IceCream', price: '4.99', aisle: 'Frozen'},
    {name: 'Romaine Lettuce', picture: 'lettuce', price: '2.99', aisle: 'Fruits & Vegetables'},
    {name: 'Live Lobster', picture: 'lobster', price: '9.55', aisle: 'Butchery'},
    {name: 'Maple Pastry Bites', picture: 'mapplepastry', price: '4.99', aisle: 'Non-Perishable'},
    {name: 'Large Naval Orange', picture: 'orange', price: '0.50', aisle: 'Fruits & Vegetables'},
    {name: 'Palm Leaf Pastry', picture: 'leafpastry', price: '6.99', aisle: 'Non-Perishable'},
    {name: 'Pea and Ham Soup', picture: 'peaandhamsoup', price: '1.99', aisle: 'Non-Perishable'},
    {name: 'Bartlett Pear', picture: 'pear', price: '0.88', aisle: 'Fruits & Vegetables'},
    {name: 'Red Pepper', picture: 'redpepper', price: '3.96', aisle: 'Fruits & Vegetables'},
    {name: 'Plain Bagel', picture: 'plainbagel', price: '3.99', aisle: 'Bakery'},
    {name: 'Pork Tenderloin, 3-Pack', picture: 'pork', price: '4.30', aisle: 'Butchery'},
    {name: 'Rib Steak, 3-Pack', picture: 'steak', price: '5.29', aisle: 'Butchery'},
    {name: 'Salmon Fillet', picture: 'salmonfillet', price: '3.42', aisle: 'Butchery'},
    {name: 'Table Salt', picture: 'salt', price: '1.76', aisle: 'Non-Perishable'},
    {name: 'Salted Butter', picture: 'butter', price: '4.69', aisle: 'Dairy & Eggs'},
    {name: 'Shredded Mozzarella Cheese Bag', picture: 'shreddedcheese', price: '5.99', aisle: 'Dairy & Eggs'},
    {name: 'Strawberry Yogurt Pack', picture: 'straberryyogurt', price: '7.49', aisle: 'Dairy & Eggs'},
    {name: 'Sugar', picture: 'sugar', price: '4.49', aisle: 'Non-Perishable'},
    {name: 'Tomato Soup', picture: 'cannedsoup', price: '3.99', aisle: 'Non-Perishable'},
    {name: 'Flaked Light Tuna', picture: 'cannedtuna', price: '1.49', aisle: 'Non-Perishable'},
    {name: 'Lean Minced Turkey', picture: 'mincedturkey', price: '2.99', aisle: 'Butchery'},
    {name: 'Unsalted Butter', picture: 'unsaltedbutter', price: '4.89', aisle: 'Dairy & Eggs'},
    {name: 'Sliced White Bread', picture: 'whitebread', price: '3.58', aisle: 'Bakery'},
    {name: 'Whole Wheat Bagel', picture: 'wholewheatbagel', price: '5.89', aisle: 'Bakery'},
    {name: 'Sliced Whole Wheat Bread', picture: 'wholewheatbread', price: '4.19', aisle: 'Bakery'},
    {name: 'Mixed Fruit Flavored Yogurt Pack', picture: 'yogurtpack', price: '5.99', aisle: 'Dairy & Eggs'},
]